BEGIN
 INSERT INTO category (category_id, name) VALUES (1, 'Captions available');
 INSERT INTO category (category_id, name) VALUES (2, 'Co-op');
 INSERT INTO category (category_id, name) VALUES (3, 'Commentary available');
 INSERT INTO category (category_id, name) VALUES (4, 'Cross-Platform Multiplayer');
 INSERT INTO category (category_id, name) VALUES (5, 'Full controller support');
 INSERT INTO category (category_id, name) VALUES (6, 'In-App Purchases');
 INSERT INTO category (category_id, name) VALUES (7, 'Includes Source SDK');
 INSERT INTO category (category_id, name) VALUES (8, 'Includes level editor');
 INSERT INTO category (category_id, name) VALUES (9, 'Local Co-op');
 INSERT INTO category (category_id, name) VALUES (10, 'Local Multi-Player');
 INSERT INTO category (category_id, name) VALUES (11, 'MMO');
 INSERT INTO category (category_id, name) VALUES (12, 'Mods');
 INSERT INTO category (category_id, name) VALUES (13, 'Mods (require HL2)');
 INSERT INTO category (category_id, name) VALUES (14, 'Multi-player');
 INSERT INTO category (category_id, name) VALUES (15, 'Online Co-op');
 INSERT INTO category (category_id, name) VALUES (16, 'Online Multi-Player');
 INSERT INTO category (category_id, name) VALUES (17, 'Partial Controller Support');
 INSERT INTO category (category_id, name) VALUES (18, 'Shared/Split Screen');
 INSERT INTO category (category_id, name) VALUES (19, 'Single-player');
 INSERT INTO category (category_id, name) VALUES (20, 'Stats');
 INSERT INTO category (category_id, name) VALUES (21, 'Steam Achievements');
 INSERT INTO category (category_id, name) VALUES (22, 'Steam Cloud');
 INSERT INTO category (category_id, name) VALUES (23, 'Steam Leaderboards');
 INSERT INTO category (category_id, name) VALUES (24, 'Steam Trading Cards');
 INSERT INTO category (category_id, name) VALUES (25, 'Steam Turn Notifications');
 INSERT INTO category (category_id, name) VALUES (26, 'Steam Workshop');
 INSERT INTO category (category_id, name) VALUES (27, 'SteamVR Collectibles');
 INSERT INTO category (category_id, name) VALUES (28, 'VR Support');
 INSERT INTO category (category_id, name) VALUES (29, 'Valve Anti-Cheat enabled');
END;
